import { authHeaders, refreshDoctorSession } from "./authClient";
import { mockMeasurements } from "./data/mockMeasurements";
import { worklistStudies } from "./data/mockStudies";
import { sampleModels, sampleRun } from "./mock/sampleRun";
import type { AgentDecision, AiModel, AiRunResponse, Measurement, PipelineRunRequest, Plane, Priority, RawMeasurements, ReviewExportRequest, ReviewExportResponse, ReviewStatus, ReviewStatusResponse, ReviewUpdateRequest, StudiesResponse, StudyRow, SystemDiagnostics } from "./appTypes";

export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8080";
const USE_MOCK = import.meta.env.VITE_USE_MOCK === "true";
const FALLBACK_RUN_ID = "demo-run-2026-001";
let demoMode = USE_MOCK;
let mockRun: AiRunResponse = sampleRun;
export const isDemoMode = () => demoMode;

function frontendTraceId() { return `frontend-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function mapPriority(value?: string): Priority { if (value === "high" || value === "alta") return "alta"; if (value === "low" || value === "baja") return "baja"; return "media"; }
function mapReviewStatus(value?: string): ReviewStatus { if (value === "aceptado" || value === "observado" || value === "descartado") return value; return "pendiente"; }
function normalizePlane(value: unknown): Plane | undefined { return value === "axial" || value === "sagittal" ? value : undefined; }
function normalizeModels(response: unknown): AiModel[] {
  if (Array.isArray(response)) return response as AiModel[];
  if (response && typeof response === "object" && "models" in response) {
    const modelsValue = (response as { models?: unknown }).models;
    if (Array.isArray(modelsValue)) return modelsValue as AiModel[];
    if (modelsValue && typeof modelsValue === "object") return Object.entries(modelsValue).map(([key, value]) => {
      const model = value && typeof value === "object" ? (value as Record<string, unknown>) : {};
      const plane = normalizePlane(model.plane);
      return { key, name: typeof model.name === "string" ? model.name : key, version: typeof model.version === "string" ? model.version : "backend", planes: plane ? [plane] : undefined, enabled: true };
    });
  }
  return sampleModels;
}
function normalizeReview(runId: string, review?: ReviewStatusResponse): ReviewStatusResponse { return { runId: review?.runId ?? runId, status: review?.status ?? "pendiente", notes: review?.notes ?? review?.observations ?? "", observations: review?.observations ?? review?.notes ?? "", reviewer: review?.reviewer ?? "", updatedAt: review?.updatedAt ?? review?.reviewedAt, reviewedAt: review?.reviewedAt ?? review?.updatedAt }; }
function toMeasurement(value: unknown, index: number): Measurement { const record = value && typeof value === "object" ? (value as Record<string, unknown>) : {}; const baseValue = typeof record.value === "number" || typeof record.value === "string" ? record.value : typeof record.aiValue === "number" || typeof record.aiValue === "string" ? record.aiValue : "N/A"; const reviewerValue = typeof record.reviewerValue === "number" || typeof record.reviewerValue === "string" || record.reviewerValue === null ? record.reviewerValue : undefined; const linkedLandmarks = Array.isArray(record.linkedLandmarks) ? record.linkedLandmarks.filter((item): item is string => typeof item === "string") : undefined; return { id: typeof record.id === "string" ? record.id : `measurement-${index}`, label: typeof record.label === "string" ? record.label : "Indicador tecnico", level: typeof record.level === "string" ? record.level : undefined, value: baseValue, aiValue: typeof record.aiValue === "number" || typeof record.aiValue === "string" ? record.aiValue : baseValue, reviewerValue, unit: typeof record.unit === "string" ? record.unit : "", confidence: typeof record.confidence === "number" ? record.confidence : undefined, plane: normalizePlane(record.plane), source: record.source === "Reviewer" || record.source === "AI" || record.source === "Placeholder" ? record.source : "AI", status: record.status === "revisado" || record.status === "editado" || record.status === "pendiente" ? record.status : "pendiente", outlier: Boolean(record.outlier), placeholder: Boolean(record.placeholder), linkedLandmarks }; }
function normalizeMeasurements(value: unknown): { normalizedMeasurements: Measurement[]; measurementsStatus?: string; measurementsDescription?: string } {
  if (Array.isArray(value)) return { normalizedMeasurements: value.map(toMeasurement) };
  if (value && typeof value === "object") { const record = value as RawMeasurements; if (Array.isArray(record.values) && record.values.length > 0) return { normalizedMeasurements: record.values.map(toMeasurement), measurementsStatus: record.status, measurementsDescription: record.description }; if (record.status === "pending_real_inference") return { normalizedMeasurements: mockMeasurements, measurementsStatus: record.status, measurementsDescription: record.description }; if (typeof record.status === "string" || typeof record.description === "string") return { normalizedMeasurements: [{ id: "pipeline-status", label: record.description ?? "Estado del pipeline tecnico", value: record.status ?? "pendiente", unit: "", source: "Placeholder", status: "pendiente", placeholder: true }], measurementsStatus: record.status, measurementsDescription: record.description }; }
  return { normalizedMeasurements: mockMeasurements };
}
function normalizeAgentDecision(agentDecision?: AgentDecision): AgentDecision { const priority = mapPriority(agentDecision?.priority ?? agentDecision?.reviewPriority); const flags = agentDecision?.flags ?? agentDecision?.agentReasons ?? []; const reasons = agentDecision?.reasons ?? agentDecision?.agentReasons ?? flags; return { ...agentDecision, status: agentDecision?.status ?? agentDecision?.agentStatus ?? "requiere_revision", priority, flags, reasons, humanReviewRequired: agentDecision?.humanReviewRequired ?? true, notClinicalDiagnosis: agentDecision?.notClinicalDiagnosis ?? true }; }
function normalizeStudyRow(value: unknown, index: number): StudyRow { const record = value && typeof value === "object" ? (value as Record<string, unknown>) : {}; const fallback = worklistStudies[index] ?? worklistStudies[0]; return { caseId: typeof record.caseId === "string" ? record.caseId : fallback.caseId, patientId: typeof record.patientId === "string" ? record.patientId : typeof record.subjectRef === "string" ? record.subjectRef : fallback.patientId, plane: normalizePlane(record.plane) ?? fallback.plane, studyDate: typeof record.studyDate === "string" ? record.studyDate : fallback.studyDate, modelKey: typeof record.modelKey === "string" ? record.modelKey : fallback.modelKey, modelStatus: typeof record.modelStatus === "string" ? record.modelStatus : fallback.modelStatus, reviewStatus: mapReviewStatus(typeof record.reviewStatus === "string" ? record.reviewStatus : fallback.reviewStatus), priority: mapPriority(typeof record.priority === "string" ? record.priority : fallback.priority), runId: typeof record.runId === "string" ? record.runId : fallback.runId }; }
function normalizeStudiesResponse(response: unknown): StudiesResponse { const record = response && typeof response === "object" ? (response as Record<string, unknown>) : {}; const itemsValue = Array.isArray(record.items) ? record.items : worklistStudies; const items = itemsValue.map(normalizeStudyRow); const pending = items.filter((item) => item.reviewStatus === "pendiente" || item.reviewStatus === "observado").length; const completed = items.filter((item) => item.reviewStatus === "aceptado").length; const flagged = items.filter((item) => item.priority === "alta" || item.reviewStatus === "observado").length; return { status: typeof record.status === "string" ? record.status : "ok", source: typeof record.source === "string" ? record.source : "frontend-normalized", items, summary: { total: items.length, pending, completed, flagged }, humanReviewRequired: true, notClinicalDiagnosis: true }; }
function validateReviewPayload(payload: ReviewUpdateRequest) { const status = payload.status; const notes = String(payload.notes ?? payload.observations ?? "").trim(); if ((status === "observado" || status === "descartado") && notes.length < 5) throw new Error("Para observar o descartar un caso, agregá una nota profesional descriptiva."); }
export function normalizeRun(run?: AiRunResponse): AiRunResponse { const runId = run?.runId ?? sampleRun.runId ?? FALLBACK_RUN_ID; const measurementState = normalizeMeasurements(run?.measurements ?? run?.measurementValues ?? sampleRun.measurements); return { ...sampleRun, ...run, runId, caseId: run?.caseId ?? sampleRun.caseId ?? "CASE-DEMO-0142", plane: run?.plane ?? sampleRun.plane ?? "sagittal", modelKey: run?.modelKey ?? sampleRun.modelKey ?? "sagittal_spider", inputPath: run?.inputPath ?? "demo/CASE-DEMO-0142", metadata: run?.metadata ?? { source: "frontend-review-workspace", uiVersion: "redesign-v1" }, agentDecision: normalizeAgentDecision(run?.agentDecision ?? run?.aiOutput?.agentDecision ?? sampleRun.agentDecision), aiOutput: run?.aiOutput, series: run?.series, masks: run?.masks, landmarks: run?.landmarks, measurements: run?.measurements ?? sampleRun.measurements, measurementValues: measurementState.normalizedMeasurements, normalizedMeasurements: measurementState.normalizedMeasurements, measurementsStatus: measurementState.measurementsStatus, measurementsDescription: measurementState.measurementsDescription, overlayPath: run?.overlayPath ?? null, review: normalizeReview(runId, run?.review), aiModuleAvailable: run?.aiModuleAvailable ?? true, degradedMode: run?.degradedMode ?? false, humanReviewRequired: run?.humanReviewRequired ?? run?.agentDecision?.humanReviewRequired ?? run?.aiOutput?.humanReviewRequired ?? true, notClinicalDiagnosis: run?.notClinicalDiagnosis ?? run?.agentDecision?.notClinicalDiagnosis ?? run?.aiOutput?.notClinicalDiagnosis ?? true }; }
async function request<T>(path: string, init?: RequestInit, fallback?: () => T, includeAuth = true): Promise<T> {
  if (USE_MOCK && fallback) { demoMode = true; return fallback(); }
  const traceId = frontendTraceId();
  const requestInit = () => ({ headers: { "Content-Type": "application/json", "X-Trace-Id": traceId, ...(includeAuth ? authHeaders() : {}), ...init?.headers }, ...init });
  try {
    let response = await fetch(`${API_BASE_URL}${path}`, requestInit());
    if (response.status === 401 && includeAuth) {
      try {
        await refreshDoctorSession();
        response = await fetch(`${API_BASE_URL}${path}`, requestInit());
      } catch {
        // If refresh fails, preserve the previous error/fallback behavior.
      }
    }
    if (!response.ok) throw new Error(`Backend respondio ${response.status}`);
    demoMode = false;
    return (await response.json()) as T;
  } catch (error) {
    if (fallback) { demoMode = true; return fallback(); }
    throw error;
  }
}
export async function getHealth() { return request<{ status: string; service?: string }>("/api/ai/health", undefined, () => ({ status: "demo", service: "mock-local" }), false); }
export async function getModels(): Promise<AiModel[]> { const response = await request<unknown>("/api/ai/models", undefined, () => sampleModels, false); return normalizeModels(response); }
export async function getStudies(): Promise<StudiesResponse> { const response = await request<unknown>("/api/studies", undefined, () => ({ status: "demo", items: worklistStudies })); return normalizeStudiesResponse(response); }
export async function getSystemDiagnostics(): Promise<SystemDiagnostics> { return request<SystemDiagnostics>("/api/system/diagnostics", undefined, () => ({ status: "demo", checkedAt: new Date().toISOString(), backend: { available: true, status: "demo" }, aiModule: { available: true, status: "demo" }, database: { available: true, status: "demo", mode: "mock" }, auth: { enabled: true, status: "demo" }, persistence: { mode: "mock", postgresEnabled: false }, humanReviewRequired: true, notClinicalDiagnosis: true }), false); }
export async function getAiCompletion(): Promise<Record<string, unknown>> { return request<Record<string, unknown>>("/api/ai/completion", undefined, () => ({ status: "demo", completionPercent: 67, humanReviewRequired: true, notClinicalDiagnosis: true }), false); }
export async function getAiRoadmap(): Promise<Record<string, unknown>> { return request<Record<string, unknown>>("/api/ai/roadmap", undefined, () => ({ status: "demo", currentMode: "contract", completed: [], pending: [] }), false); }
export async function getAiEvaluationContract(): Promise<Record<string, unknown>> { return request<Record<string, unknown>>("/api/ai/evaluation/contract", undefined, () => ({ status: "demo", metrics: [] }), false); }
export async function getAiEvaluationSummary(): Promise<Record<string, unknown>> { return request<Record<string, unknown>>("/api/ai/evaluation/summary", undefined, () => ({ status: "demo", reportCount: 0 }), false); }
export async function warmupSystem(): Promise<SystemDiagnostics> { return request<SystemDiagnostics>("/api/system/warmup", { method: "POST" }, () => ({ status: "demo", checkedAt: new Date().toISOString(), aiModule: { available: true, status: "demo", message: "warmup demo" } }), false); }
export async function getDemoStudyReview(): Promise<any> { return request<any>("/api/studies/demo-review", undefined, () => null); }
export async function runPipeline(payload: PipelineRunRequest): Promise<AiRunResponse> { const requestPayload: PipelineRunRequest = { caseId: payload.caseId, plane: payload.plane, modelKey: payload.modelKey, inputPath: payload.inputPath ?? "demo/CASE-DEMO-0142", metadata: payload.metadata ?? { source: "frontend-review-workspace", uiVersion: "redesign-v1" } }; const response = await request<AiRunResponse>("/api/ai/pipeline/run", { method: "POST", body: JSON.stringify(requestPayload) }, () => { mockRun = normalizeRun({ ...sampleRun, ...requestPayload, runId: `demo-run-${Date.now()}`, createdAt: new Date().toISOString() }); return mockRun; }); const normalized = normalizeRun(response); try { const report = await getAgentReport(normalized.runId ?? FALLBACK_RUN_ID); return normalizeRun({ ...normalized, ...report, agentDecision: report.agentDecision ?? normalized.agentDecision }); } catch { return normalized; } }
export async function getAgentReport(runId: string): Promise<AiRunResponse> { const response = await request<AiRunResponse>(`/api/ai/agent/report/${runId}`, undefined, () => normalizeRun({ ...mockRun, runId })); return normalizeRun(response); }
export async function updateReview(runId: string, payload: ReviewUpdateRequest): Promise<ReviewStatusResponse> { validateReviewPayload(payload); return request<ReviewStatusResponse>(`/api/ai/review/${runId}`, { method: "PATCH", body: JSON.stringify({ status: payload.status, notes: payload.notes ?? payload.observations ?? "", observations: payload.observations ?? payload.notes ?? "", reviewer: payload.reviewer ?? "Reviewer" }) }, () => { mockRun = { ...normalizeRun(mockRun), review: { runId, status: payload.status, notes: payload.notes ?? payload.observations ?? "", observations: payload.observations ?? payload.notes ?? "", reviewer: payload.reviewer ?? "Reviewer", updatedAt: new Date().toISOString() } }; return mockRun.review ?? normalizeReview(runId, undefined); }).then((review) => normalizeReview(runId, review)); }
export async function exportReviewReport(runId: string, payload: ReviewExportRequest): Promise<ReviewExportResponse> { return request<ReviewExportResponse>(`/api/ai/review/${runId}/export`, { method: "POST", body: JSON.stringify(payload) }); }
